version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/t_app
      - bundle_path:/bundle
    stdin_open: true
    tty: true
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      BUNDLE_PATH: /bundle
      TZ: Asia/Tokyo
volumes:
  bundle_path:
